### ISSUE TITLE
The following assertion was thrown during paint():

### ISSUE THREAD

**Issue by Yeikel200** [xsahil03x/before_after#1]
Hello, before I thank you all for creating this plugin that is great. The example compiles me well and the application will be opened but when I start it is this in the debug console:

`Restarted application in 24.145ms.
I/flutter ( 7025): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 7025): The following assertion was thrown during paint():
I/flutter ( 7025): 'package:flutter/src/material/slider_theme.dart': Failed assertion: line 1469 pos 12:
I/flutter ( 7025): 'parentBox.size.height >= trackHeight': is not true.
I/flutter ( 7025):
I/flutter ( 7025): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7025): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7025): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7025):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 7025):
I/flutter ( 7025): When the exception was thrown, this was the stack:
I/flutter ( 7025): #2      _RoundedRectSliderTrackShape&SliderTrackShape&BaseSliderTrackShape.getPreferredRect 
I/flutter ( 7025): #3      _RenderSlider.paint 
I/flutter ( 7025): #4      RenderObject._paintWithContext 
I/flutter ( 7025): #5      PaintingContext.paintChild 
I/flutter ( 7025): #6      _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint 
I/flutter ( 7025): #7      RenderStack.paintStack 
I/flutter ( 7025): #8      RenderStack.paint 
I/flutter ( 7025): #9      RenderObject._paintWithContext 
I/flutter ( 7025): #10     PaintingContext.paintChild 
I/flutter ( 7025): #11     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint 
I/flutter ( 7025): #12     RenderFlex.paint 
I/flutter ( 7025): #13     RenderObject._paintWithContext 
I/flutter ( 7025): #14     PaintingContext.paintChild 
I/flutter ( 7025): #15     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint 
I/flutter ( 7025): #16     RenderCustomMultiChildLayoutBox.paint 
I/flutter ( 7025): #17     RenderObject._paintWithContext 
I/flutter ( 7025): #18     PaintingContext.paintChild 
I/flutter ( 7025): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #20     _RenderInkFeatures.paint 
I/flutter ( 7025): #21     RenderObject._paintWithContext 
I/flutter ( 7025): #22     PaintingContext.paintChild 
I/flutter ( 7025): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #24     PaintingContext.pushLayer 
I/flutter ( 7025): #25     RenderPhysicalModel.paint 
I/flutter ( 7025): #26     RenderObject._paintWithContext 
I/flutter ( 7025): #27     PaintingContext.paintChild 
I/flutter ( 7025): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #29     RenderObject._paintWithContext 
I/flutter ( 7025): #30     PaintingContext.paintChild 
I/flutter ( 7025): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #32     RenderObject._paintWithContext 
I/flutter ( 7025): #33     PaintingContext._repaintCompositedChild 
I/flutter ( 7025): #34     PaintingContext.repaintCompositedChild 
I/flutter ( 7025): #35     PaintingContext._compositeChild 
I/flutter ( 7025): #36     PaintingContext.paintChild 
I/flutter ( 7025): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #38     RenderObject._paintWithContext 
I/flutter ( 7025): #39     PaintingContext.paintChild 
I/flutter ( 7025): #40     RenderAnimatedOpacity.paint 
I/flutter ( 7025): #41     RenderObject._paintWithContext 
I/flutter ( 7025): #42     PaintingContext.paintChild 
I/flutter ( 7025): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #44     RenderFractionalTranslation.paint 
I/flutter ( 7025): #45     RenderObject._paintWithContext 
I/flutter ( 7025): #46     PaintingContext.paintChild 
I/flutter ( 7025): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #48     RenderObject._paintWithContext 
I/flutter ( 7025): #49     PaintingContext._repaintCompositedChild 
I/flutter ( 7025): #50     PaintingContext.repaintCompositedChild 
I/flutter ( 7025): #51     PaintingContext._compositeChild 
I/flutter ( 7025): #52     PaintingContext.paintChild 
I/flutter ( 7025): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #54     RenderObject._paintWithContext 
I/flutter ( 7025): #55     PaintingContext.paintChild 
I/flutter ( 7025): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #57     RenderOffstage.paint 
I/flutter ( 7025): #58     RenderObject._paintWithContext 
I/flutter ( 7025): #59     PaintingContext.paintChild 
I/flutter ( 7025): #60     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint 
I/flutter ( 7025): #61     RenderStack.paintStack 
I/flutter ( 7025): #62     RenderStack.paint 
I/flutter ( 7025): #63     RenderObject._paintWithContext 
I/flutter ( 7025): #64     PaintingContext.paintChild 
I/flutter ( 7025): #65     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #66     RenderObject._paintWithContext 
I/flutter ( 7025): #67     PaintingContext.paintChild 
I/flutter ( 7025): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #69     RenderObject._paintWithContext 
I/flutter ( 7025): #70     PaintingContext.paintChild 
I/flutter ( 7025): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #72     RenderObject._paintWithContext 
I/flutter ( 7025): #73     PaintingContext.paintChild 
I/flutter ( 7025): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #75     RenderPointerListener.paint 
I/flutter ( 7025): #76     RenderObject._paintWithContext 
I/flutter ( 7025): #77     PaintingContext.paintChild 
I/flutter ( 7025): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #79     RenderCustomPaint.paint 
I/flutter ( 7025): #80     RenderObject._paintWithContext 
I/flutter ( 7025): #81     PaintingContext.paintChild 
I/flutter ( 7025): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint 
I/flutter ( 7025): #83     RenderObject._paintWithContext 
I/flutter ( 7025): #84     PaintingContext.paintChild 
I/flutter ( 7025): #85     RenderView.paint 
I/flutter ( 7025): #86     RenderObject._paintWithContext 
I/flutter ( 7025): #87     PaintingContext._repaintCompositedChild 
I/flutter ( 7025): #88     PaintingContext.repaintCompositedChild 
I/flutter ( 7025): #89     PipelineOwner.flushPaint 
I/flutter ( 7025): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame 
I/flutter ( 7025): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
I/flutter ( 7025): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
I/flutter ( 7025): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
I/flutter ( 7025): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
I/flutter ( 7025): #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
I/flutter ( 7025): #104    _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter ( 7025): #105    _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter ( 7025): #106    _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 7025): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter ( 7025):
I/flutter ( 7025): The following RenderObject was being processed when the exception was fired: _RenderSlider#43b88:
I/flutter ( 7025):   creator: _SliderRenderObjectWidget ← Slider ← SliderTheme ← Positioned ← Stack ← BeforeAfter ←
I/flutter ( 7025):     Column ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ←
I/flutter ( 7025):     DefaultTextStyle ← ⋯
I/flutter ( 7025):   parentData: top=0.0; right=0.0; bottom=0.0; left=0.0; offset=Offset(0.0, 0.0) (can use size)
I/flutter ( 7025):   constraints: BoxConstraints(w=48.0, h=0.0)
I/flutter ( 7025):   semantic boundary
I/flutter ( 7025):   size: Size(48.0, 0.0)
I/flutter ( 7025): This RenderObject has no descendants.
I/flutter ( 7025): ════════════════════════════════════════════════════════════════════════════════════════════════════
`

> execute flutter doctor -v

`[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [VersiÃ³n 10.0.17763.615],    locale es-CU)
    • Flutter version 1.7.8+hotfix.3 at C:\src\flutter
    • Framework revision b712a172f9 (10 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Programas\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = D:\Programas\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\yeikel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected device (1 available)
    • SM T580 • 52037296ea36c3b1 • android-arm • Android 8.1.0 (API 27)

• No issues found!
`

**Comment by mannprerak2** [comment]
This seems to be happening due to the Slider having this as its parent (above ```SliderTheme```)
```dart
Positioned(
top:0.0
bottom..
.
.)
```
But we need this ```Positioned``` widget to ensure Slider is of the same width as the stack's biggest element.
This error, however, **doesn't show up if** we wrap BeforeAfter in an Expanded or Flex Widget

**Comment by xsahil03x** [comment]
@mannprerak2 this has been fixed in the latest release. Instead of making the slider track transparent. I just set its height to 0. It was mentioned in the documentation.

```The track painting can be skipped by specifying 0 for [trackHeight].
```
