### ISSUE TITLE
Request to add Product in Start Flutter

### ISSUE THREAD

**Issue by maheshwari-1153** [xsahil03x/before_after#2]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website.

Looking forward to hear from you.

**Comment by xsahil03x** [comment]
Hey Maheshwari,

I am open to any help to the flutter community. If you found this package useful, you can showcase it on Start Flutter.

Regards,
Sahil

**Comment by maheshwari-1153** [comment]
Thanks, I will let you know, once we update the product on website.

**Comment by maheshwari-1153** [comment]
Updated the product in StartFlutter.
Please check:https://startflutter.com/themes/before-after/
Thankyou

**Comment by xsahil03x** [comment]
Your welcome 😊
