### ISSUE TITLE
Is it possible to use images from internet?

### ISSUE THREAD

**Issue by rakhimian** [xsahil03x/before_after#25]
<img width="460" alt="Снимок экрана 2022-02-13 в 19 13 30" src="https://user-images.githubusercontent.com/13000093/153763155-a7df46b6-387e-4f79-98f5-07d52930eb99.png">
<img width="718" alt="Снимок экрана 2022-02-13 в 19 13 37" src="https://user-images.githubusercontent.com/13000093/153763157-4b31fd60-bd98-43b3-8d23-a8e6c6a03cae.png">

**Comment by xsahil03x** [comment]
Looks like you forgot the internet permission.
