### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by felipecastrosales** [xsahil03x/before_after#27]
Currently this package is not compatible with Dart 3.0.0.

![image](https://github.com/xsahil03x/before_after/assets/59374587/5d93be9f-31b7-4429-a2cc-8a59238c44db)

Is there any predictability for the tweak or any forks in the community?

**Comment by xsahil03x** [comment]
yes, latest version here: [v3.0.0](https://pub.dev/packages/before_after/versions/3.0.0)
