### ISSUE TITLE
Move track and thumb out of Widget

### ISSUE THREAD

**Issue by hadi7khan** [xsahil03x/before_after#31]
We must be change the divider position to negative as well like take divider and handle out of BeforeAfter , from top or bottom. Just like image added below.
![Screenshot from 2023-08-02 17-23-37](https://github.com/xsahil03x/before_after/assets/68601505/bde00312-14ae-4ce1-a3af-4d9f3818eea6)

**Comment by xsahil03x** [comment]
@hadi7khan can you share the image and the exact issue you are facing?
