### ISSUE TITLE
Privacy manifest file for iOS is missing

### ISSUE THREAD

**Issue by oremlawi** [xsahil03x/before_after#33]
To ensure a smooth app update and avoid App Store rejection, kindly consider adding a privacy manifest to your library. This helps developers reflect data collection practices in our own manifests.

[Apple documentation.](https://developer.apple.com/support/third-party-SDK-requirements/)

**Comment by xsahil03x** [comment]
@oremlawi BeforeAfter is not part of that list and it's not even a plugin. It's a simple dart package so I don't think we need to do anything here. Thanks
