### ISSUE TITLE
Height and width simultaneously crop the image. Padding is not adjustable?

### ISSUE THREAD

**Issue by jessicamrbr** [xsahil03x/before_after#8]
Hello, congratulations on the excellent work!

I am trying to adjust the height and width simultaneously, but the image is cropped. I took a look at the code and it seems to be on purpose, could it be changed?

It would also be interesting for padding to be controlled externally, giving more freedom, does it make sense?

**Comment by jessicamrbr** [comment]
@xsahil03x ?

**Comment by quyvsquy** [comment]
@xsahil03x ?

**Comment by juanmajh96** [comment]
I'm going to check it

**Comment by xsahil03x** [comment]
Added in [v3.0.0](https://pub.dev/packages/before_after/versions/3.0.0)
